# Generated by Django 2.0.2 on 2018-02-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='slug',
            field=models.SlugField(default='people_slug'),
        ),
        migrations.AddField(
            model_name='walk',
            name='slug',
            field=models.SlugField(default='walk_slug'),
        ),
    ]
