# Generated by Django 2.0.2 on 2018-02-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_auto_20180211_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='walk',
            field=models.ForeignKey(default='chri', on_delete=django.db.models.deletion.CASCADE, to='walks.Walk'),
        ),
    ]
