# Generated by Django 2.0.2 on 2018-02-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_people_walk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='walk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='walks.Walk'),
        ),
    ]
