# Generated by Django 2.0.2 on 2018-02-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0004_auto_20180211_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='walk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.Walk'),
        ),
    ]
